version: '3.8'

services:
  litellm:
    env_file: .env.litellm
    image: ghcr.io/berriai/litellm:main-latest
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    ports:
      - '4000:4000'
    command: --config /app/config.yaml --detailed_debug
    restart: unless-stopped

  openwebui:
    env_file: .env.openwebui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/app/backend/data
    ports:
      - '${OPEN_WEBUI_PORT-3000}:8080'
    depends_on:
      - litellm
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  litellm: {}
